### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by JMike295** [gildaswise/HorizontalCounter#2]
Is there a way i can customize the layout? I want to use icons on buttons to increment and decrement. Thank you

**Comment by gildaswise** [comment]
Hey! I'm so sorry for the delay. I just published an update to Kotlin and will start working on your request now, should be ready today!

**Comment by gildaswise** [comment]
Done, fixed [here](https://github.com/gildaswise/HorizontalCounter/commit/9ecedb1151b84ddd0249e10443cdd26691d5cdbf)!
